/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant firstRes = new Restaurant("InDoor");
        firstRes.setStars(3);
        firstRes.setPrice(4);
        firstRes.addReview("Amazing Restaurant" , "Hana", 5);
        System.out.println(firstRes);
    }
}