/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test public void testLinter() {
        String testPath = "./src/test/resources/test.js";
        ArrayList<String> outList = new ArrayList<String>();
        outList.add("Line 1 : Missing semicolon.");
        outList.add("Line 5 : Missing semicolon.");
        outList.add("Line 9 : Missing semicolon.");
        System.out.println(outList.equals(App.linter(testPath)));
        assertEquals( outList ,App.linter(testPath));
    }
}